### ISSUE TITLE
Gradle sync failed: Cause: javacTask

### ISSUE THREAD

**Issue by pavelaizen** [Archinamon/android-gradle-aspectj#101]
**Gradle sync failed: Cause: javacTask**

Same issue with:
classpath 'com.android.tools.build:gradle:3.5.2'
classpath "com.archinamon:android-gradle-aspectj:3.2.0"

@Archinamon can you assist please?

**Comment by nisrulz** [comment]
As it says in the readme under changelog, you need to use the v4.0.0 of the lib.

<img width="476" alt="Screen Shot 2019-12-08 at 4 23 30 PM" src="https://user-images.githubusercontent.com/2096087/70391599-2bb27480-19d7-11ea-88ff-7a05f3985aff.png">

Have you tried the below:

```groovy
classpath 'com.android.tools.build:gradle:3.5.2'
classpath "com.archinamon:android-gradle-aspectj:4.0.0"
```
