### ISSUE TITLE
com/archinamon/api/ClasspathFileCollection.getBuildDependencies()Lorg/gradle/api/tasks/TaskDependency; is abstract

### ISSUE THREAD

**Issue by rahuljain88** [Archinamon/android-gradle-aspectj#102]
When we used Android Gradle version  classpath 'com.android.tools.build:gradle:3.5.1' with         classpath "com.archinamon:android-gradle-aspectj:4.0.0" .

I am getting below compile time error : 

Method com/archinamon/api/ClasspathFileCollection.getBuildDependencies()Lorg/gradle/api/tasks/TaskDependency; is abstract

**Comment by richard-bogdan-bitrise** [comment]
For me setting the wrapper version to 6.0 helped.

Try updating the gradle-wrapper.properties:
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.0-all.zip`

**Comment by kzsolti** [comment]
We are also getting this error if I try to update the plugin version to 4.0.0. We are using Gradle 5.4.1as it is the officially supported version by the latest Android Gradle plugin according to the documentation: https://developer.android.com/studio/releases/gradle-plugin#updating-gradle

I think this plugin should be backward compatible with Gradle 5.x at least until the Android plugin drops support for it.

**Comment by cyangibm** [comment]
> We are also getting this error if I try to update the plugin version to 4.0.0. We are using Gradle 5.4.1 as it is the officially supported version by the latest Android Gradle plugin according to the documentation: https://developer.android.com/studio/releases/gradle-plugin#updating-gradle
> 
> I think this plugin should be backward compatible with Gradle 5.x at least until the Android plugin drops support for it.

Yes.  We have to support min SDK >= 16, and below config.  The build error is a blocker..

Plugin version 4.1.0
AGP version 3.6.3
Gradle version 5.6.4
