### ISSUE TITLE
Method com/archinamon/api/ClasspathFileCollection.getBuildDependencies()Lorg/gradle/api/tasks/TaskDependency; is abstract

### ISSUE THREAD

**Issue by m0skit0** [Archinamon/android-gradle-aspectj#115]
First of all thanks a lot for your work!

I get this error when trying to build project

```
Method com/archinamon/api/ClasspathFileCollection.getBuildDependencies()Lorg/gradle/api/tasks/TaskDependency; is abstract
```

Plugin version 4.1.0
AGP version 3.6.3
Gradle version 5.6.4

**Comment by dansaka** [comment]
+1

**Comment by m0skit0** [comment]
Updating Gradle to 6.3 and min SDK to 24 solves this error.

**Comment by cyangibm** [comment]
Is there a solution for below config?  I need to support that Gradle version, and min SDK 16

Plugin version 4.1.0
AGP version 3.6.3
Gradle version 5.6.4
