### ISSUE TITLE
Help me!!!  xxx is defined multiple times:

### ISSUE THREAD

**Issue by averyzhong** [Archinamon/android-gradle-aspectj#121]
`aspectj {
    ajc = "1.9.5" // default value
    java = JavaVersion.VERSION_1_8 // default value
    includeAllJars = false // default value
    includeJar 'retrofit-2.6.0'
}`

> Type retrofit2.BuiltInConverters$BufferingResponseBodyConverter is defined multiple times: /Users/avery/AndroidStudioProjects/NewsPlus/app/build/intermediates/mixed_scope_dex_archive/debug/out/39c69c20d0f46eb9c642565d840e64638fff1ba8ae6d8e0b8a4318828d8ef349_5.jar:classes.dex, /Users/avery/AndroidStudioProjects/NewsPlus/app/build/intermediates/mixed_scope_dex_archive/debug/out/cbf7c823e7225e02a34d087be63f58c4e3f372e4b663235e195d08fd9398358c_5.jar:classes.dex

**Comment by sho0007** [comment]
해결하셨나요?

**Comment by sho0007** [comment]
라이브러리 정리하면됩니다
