### ISSUE TITLE
3.3.0 pom is missing at jcenter

### ISSUE THREAD

**Issue by divankov** [Archinamon/android-gradle-aspectj#83]
http://jcenter.bintray.com/com/archinamon/android-gradle-aspectj/3.3.0/
There is only android-gradle-aspectj-3.3.0.jar
maven-metadata.xml also doesn't include 3.3.0 http://jcenter.bintray.com/com/archinamon/android-gradle-aspectj/:maven-metadata.xml

**Comment by neyguvj** [comment]
POM is still missing

**Comment by Archinamon** [comment]
Updated to 3.3.3
Dependency resolves OK with gradle. Try it please

**Comment by divankov** [comment]
Still doesn't resolve for me and
http://jcenter.bintray.com/com/archinamon/android-gradle-aspectj/3.3.3/
contains no pom.
Could it be resolving via your local cache?

**Comment by Archinamon** [comment]
Added pom file for 3.3.3 release.

**Comment by divankov** [comment]
Great, 3.3.3 resolves for me now!
