### ISSUE TITLE
Question: Does it support Android Studio 3.2 and Gradle 4.4 and up?

### ISSUE THREAD

**Issue by duanjason** [Archinamon/android-gradle-aspectj#85]
According to the readme file, "May not work properly for AS 3.0 :(", is this still true? Does it support the latest Android Studio 3.2 and Gradle 4.6? If no, what is the plan to support them?

Thanks

**Comment by luanalbineli** [comment]
Hi @duanjason , I'm believe no. I'm currently trying to use it with AS 3.2.1, and I'm facing the problem reported in #82

**Comment by Archinamon** [comment]
This warning was about IDE syntax plugin. Gradle plugin still works fine. If you're facing "no such method error" — try to update Android Gradle plugin to 3.0.1 at least or higher.
