### ISSUE TITLE
Unable to find method 'org.gradle.api.file.ProjectLayout.files([Ljava/lang/Object;)Lorg/gradle/api/file/FileCollection;'.

### ISSUE THREAD

**Issue by SynergySaugat** [Archinamon/android-gradle-aspectj#87]
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)</li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)</li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
same issue here...

repositories {
    // ...
    maven { url "https://jitpack.io" }
    maven { url 'https://github.com/Archinamon/GradleAspectJ-Android/raw/master' }
}
    implementation "com.archinamon:android-gradle-aspectj:3.3.0"
apply plugin: 'com.archinamon.aspectj'
        classpath 'com.archinamon:android-gradle-aspectj:3.3.0'

_Originally posted by @SynergySaugat in https://github.com/Archinamon/android-gradle-aspectj/issues/82#issuecomment-440942208_

**Comment by Archinamon** [comment]
You have to use Android Gradle plugin 3.0.1 at least. 3.2.* is better.
And you don't need to use `implementation` notation within dependencies block.
